// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxLqj319lJm2h0JzXguRu35de2pm-QIo',
    appId: '1:277365665132:web:8f6ddb314817026bb19749',
    messagingSenderId: '277365665132',
    projectId: 'telu-project',
    authDomain: 'telu-project.firebaseapp.com',
    storageBucket: 'telu-project.appspot.com',
    measurementId: 'G-NE92MLZCH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKwHDhHEKXBJwHweDEZSh1vOkrVP9e-Go',
    appId: '1:277365665132:android:18b6c730a1c0709ab19749',
    messagingSenderId: '277365665132',
    projectId: 'telu-project',
    storageBucket: 'telu-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhR1xSSzx4bJZ4KyKMOyrawuMowfmwQNc',
    appId: '1:277365665132:ios:e1d5eef8f3e6dc97b19749',
    messagingSenderId: '277365665132',
    projectId: 'telu-project',
    storageBucket: 'telu-project.appspot.com',
    iosBundleId: 'com.example.teluProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhR1xSSzx4bJZ4KyKMOyrawuMowfmwQNc',
    appId: '1:277365665132:ios:e1d5eef8f3e6dc97b19749',
    messagingSenderId: '277365665132',
    projectId: 'telu-project',
    storageBucket: 'telu-project.appspot.com',
    iosBundleId: 'com.example.teluProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxLqj319lJm2h0JzXguRu35de2pm-QIo',
    appId: '1:277365665132:web:c6b3e2dcf0fc9832b19749',
    messagingSenderId: '277365665132',
    projectId: 'telu-project',
    authDomain: 'telu-project.firebaseapp.com',
    storageBucket: 'telu-project.appspot.com',
    measurementId: 'G-5XN0KR31E7',
  );
}
